version: '3'
services:
  # Dev container
  node:
    build: .
    command: sleep infinity
    environment:
      LDAP_PROTOCOL: ldap
      LDAP_HOST1: ldap1
      LDAP_HOST2: ldap2
      LDAP_PORT1: 1389
      LDAP_PORT2: 389
      LDAP_BIND_DN: cn=admin,dc=example,dc=org
      LDAP_BIND_PWD: foobar
      LDAP_BASE_DN: dc=example,dc=org
    volumes:
      - ..:/workspaces/ldap-explorer:cached
      - pre-commit:/home/node/.cache/pre-commit
  # Dummy LDAP server for testing purposes
  # https://hub.docker.com/r/bitnami/openldap/
  # https://github.com/bitnami/bitnami-docker-openldap
  ldap1:
    image: bitnami/openldap:2
    ports:
      - 1389:1389
      - 1636:1636
    environment:
      LDAP_ADMIN_USERNAME: admin
      LDAP_ADMIN_PASSWORD: foobar
      LDAP_USERS: user1,user2,user3
      LDAP_PASSWORDS: pwd1,pwd2,pwd3
    volumes:
      - ldap1_data:/bitnami/openldap
  # Another dummy LDAP server ; this one also supports TLS
  # https://hub.docker.com/r/osixia/openldap
  # https://github.com/osixia/docker-openldap
  ldap2:
    image: osixia/openldap:1.5.0
    ports:
      - 2389:389
      - 2636:636
    environment:
      LDAP_ADMIN_PASSWORD: foobar
      LDAP_BASE_DN: dc=example,dc=org
      LDAP_DOMAIN: example.org
      LDAP_ORGANISATION: Example
      LDAP_OPENLDAP_UID: 1000
      LDAP_OPENLDAP_GID: 1000
    volumes:
      - ldap2_db:/var/lib/ldap
      - ldap2_conf:/etc/ldap/slapd.d
    # Fixes https://github.com/osixia/docker-openldap/issues/179
    command: --copy-service
volumes:
  pre-commit:
  ldap1_data:
  ldap2_db:
  ldap2_conf:
