version: '3'
services:
  # Dev container
  node:
    build: .
    command: sleep infinity
    environment:
      LDAP_PROTOCOL: ldap
      LDAP_HOST: ldap
      LDAP_PORT: 1389
      LDAP_BIND_DN: cn=admin,dc=example,dc=org
      LDAP_BIND_PWD: foobar
      LDAP_BASE_DN: dc=example,dc=org
    volumes:
      - ..:/workspaces/ldap-explorer:cached
      - pre-commit:/home/node/.cache/pre-commit
  # Dummy LDAP server for testing purposes
  # https://hub.docker.com/r/bitnami/openldap/
  ldap:
    image: bitnami/openldap:2
    ports:
      - 1389:1389
      - 1636:1636
    environment:
      LDAP_ADMIN_USERNAME: admin
      LDAP_ADMIN_PASSWORD: foobar
      LDAP_USERS: user1,user2,user3
      LDAP_PASSWORDS: pwd1,pwd2,pwd3
    volumes:
      - openldap_data:/bitnami/openldap
volumes:
  pre-commit:
  openldap_data:
    driver: local
