name: Build
on: [push]
jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        # Same version of nodejs as that used for
        # - vscode itself https://github.com/Microsoft/vscode/wiki/How-to-Contribute#prerequisites
        # - dev container .devcontainer/Dockerfile
        node-version: 20.x
    - run: npm install
    - run: xvfb-run -a npm test
      if: runner.os == 'Linux'
    - run: npm test
      if: runner.os != 'Linux'
    - run: node_modules/.bin/vsce package
    - name: Upload package as artifact
      uses: actions/upload-artifact@v4
      with:
        path: *.vsix
