name: Build
on: [push]
jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        # Same version of nodejs as that used for
        # - vscode itself https://github.com/Microsoft/vscode/wiki/How-to-Contribute#prerequisites
        # - dev container .devcontainer/Dockerfile
        node-version: 20.x
    - run: npm install
    - run: xvfb-run -a npm test
      if: runner.os == 'Linux'
    - run: npm test
      if: runner.os != 'Linux'
    - run: ls
    - run: ls node_modules
    - run: ls node_modules/.bin
    - run: which vsce
    - run: vsce package
